const configuredBaseUrl = import.meta.env.VITE_API_BASE_URL || "http://janu1g3okwroefybl3f4tvmw.195.35.7.46.sslip.io";

export const API_ORIGIN = configuredBaseUrl.replace(/\/$/, "");
export const API_BASE_URL = `${API_ORIGIN}/api`;

export const API = {
  auth: {
    adminLogin: "/admin/auth/login",
    sendOtp: "/auth/send-otp",
    verifyOtp: "/auth/verify-otp",
    mergeGuest: "/auth/merge-guest",
    profile: "/auth/profile",
    profilePhotoUploadUrl: "/auth/profile/photo/upload-url",
    profilePhotoConfirm: "/auth/profile/photo/confirm",
    account: "/auth/account",
    logout: "/auth/logout",
  },
  languages: {
    publicList: "/languages",
    adminList: "/admin/languages",
    detail: (id: string | number) => `/admin/languages/${id}`,
    status: (id: string | number) => `/admin/languages/${id}/status`,
  },
  categories: {
    publicList: "/categories",
    publicDetail: (id: string | number) => `/categories/${id}`,
    subcategories: (id: string | number) => `/categories/${id}/subcategories`,
    videos: (id: string | number) => `/categories/${id}/videos`,
    adminList: "/admin/categories",
    detail: (id: string | number) => `/admin/categories/${id}`,
    status: (id: string | number) => `/admin/categories/${id}/status`,
    sort: "/admin/categories/sort",
  },
  channels: {
    publicList: "/channels",
    adminList: "/admin/channels",
    detail: (id: string | number) => `/admin/channels/${id}`,
  },
  news: {
    list: "/news",
    adminList: "/admin/news",
    adminStats: "/admin/news/stats",
    detail: (id: string | number) => `/admin/news/${id}`,
    approve: (id: string | number) => `/admin/news/${id}/approve`,
    reject: (id: string | number) => `/admin/news/${id}/reject`,
    schedule: (id: string | number) => `/admin/news/${id}/schedule`,
    feature: (id: string | number) => `/admin/news/${id}/feature`,
    bulk: "/admin/news/bulk",
    uploadUrl: (id: string | number) => `/news/${id}/upload-url`,
    uploadConfirm: (id: string | number) => `/news/${id}/upload-confirm`,
    thumbnailUploadUrl: (id: string | number) => `/news/${id}/thumbnail/upload-url`,
    thumbnailConfirm: (id: string | number) => `/news/${id}/thumbnail/confirm`,
    view: (id: string | number) => `/news/${id}/view`,
    like: (id: string | number) => `/news/${id}/like`,
    share: (id: string | number) => `/news/${id}/share`,
    comments: (id: string | number) => `/news/${id}/comments`,
    categories: (id: string | number) => `/news/${id}/categories`,
  },
  users: {
    adminList: "/admin/users",
    adminStats: "/admin/users/stats",
    detail: (id: string | number) => `/admin/users/${id}`,
    status: (id: string | number) => `/admin/users/${id}/status`,
  },
  complaints: {
    adminList: "/admin/complaints",
    adminStats: "/admin/complaints/stats",
    detail: (id: string | number) => `/admin/complaints/${id}`,
    status: (id: string | number) => `/admin/complaints/${id}/status`,
    imageUploadUrl: "/admin/complaints/image/upload-url",
    messages: (id: string | number) => `/admin/complaints/${id}/messages`,
    timeline: (id: string | number) => `/admin/complaints/${id}/timeline`,
  },
  complaintCategories: {
    list: "/admin/complaint-categories",
    stats: "/admin/complaint-categories/stats",
    uploadUrl: "/admin/complaint-categories/upload-url",
    detail: (id: string | number) => `/admin/complaint-categories/${id}`,
    status: (id: string | number) => `/admin/complaint-categories/${id}/status`,
    subCategories: "/admin/complaint-categories/sub-categories",
    subCategoryDetail: (id: string | number) => `/admin/complaint-categories/sub-categories/${id}`,
    subCategoryStatus: (id: string | number) => `/admin/complaint-categories/sub-categories/${id}/status`,
    assignRules: "/admin/complaint-categories/assign-rules",
    assignRuleStats: "/admin/complaint-categories/assign-rules/stats",
    assignRuleDetail: (id: string | number) => `/admin/complaint-categories/assign-rules/${id}`,
    assignRuleStatus: (id: string | number) => `/admin/complaint-categories/assign-rules/${id}/status`,
  },
  locations: {
    summary: "/admin/locations/summary",
    states: "/admin/locations/states",
    stateDetail: (id: string | number) => `/admin/locations/states/${id}`,
    stateStatus: (id: string | number) => `/admin/locations/states/${id}/status`,
    districts: "/admin/locations/districts",
    districtDetail: (id: string | number) => `/admin/locations/districts/${id}`,
    districtStatus: (id: string | number) => `/admin/locations/districts/${id}/status`,
    areas: "/admin/locations/areas",
    areaDetail: (id: string | number) => `/admin/locations/areas/${id}`,
    areaStatus: (id: string | number) => `/admin/locations/areas/${id}/status`,
  },
  regions: "/regions",
} as const;
