export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  NEWS_ALL: "/news/all",
  NEWS_ADMIN: "/news/admin",
  NEWS_ADD: "/news/add",
  CATEGORIES: "/categories",
  NEWS_TAGS: "/news-tags",
  COMPLAINTS: "/complaints",
  USERS: "/users",
  CHANNELS: "/channels",
  CHANNELS_ADD: "/channels/add",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  REFERRALS: "/referrals",
  OFFERS: "/offers",
  LISTINGS: "/listings",
  MONETIZATION: "/monetization",
  SYS_LANGUAGE: "/system/language",
  SYS_LANGUAGE_ADD: "/system/language/add",
  SYS_LOCATION: "/system/location",
  SYS_STATES: "/system/location/states",
  SYS_STATES_ADD: "/system/location/states/add",
  SYS_DISTRICTS: "/system/location/districts",
  SYS_AREAS: "/system/location/areas",
  SYS_AUDIT: "/system/audit-logs",
  SYS_BACKUP: "/system/backup",
  SYS_ROLES: "/system/roles",
  SETTINGS: "/settings",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
