export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  NEWS_ALL: "/news/all",
  NEWS_ADMIN: "/news/admin",
  NEWS_ADD: "/news/add",
  CATEGORIES: "/categories",
  CATEGORIES_ADD: "/categories/add",
  CATEGORIES_EDIT: (id: string) => `/categories/${id}/edit`,
  NEWS_TAGS: "/news-tags",
  COMPLAINTS: "/complaints",
  USERS: "/users",
  CHANNELS: "/channels",
  CHANNELS_ADD: "/channels/add",
  CHANNELS_EDIT: (id: string) => `/channels/${id}/edit`,
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  NOTIFICATIONS_ADD: "/notifications/add",
  NOTIFICATIONS_VIEW: (id: string) => `/notifications/${id}`,
  NOTIFICATIONS_EDIT: (id: string) => `/notifications/${id}/edit`,
  REFERRALS: "/referrals",
  OFFERS: "/offers",
  OFFERS_ADD: "/offers/add",
  LISTINGS: "/listings",
  LISTINGS_ADD: "/listings/add",
  MONETIZATION: "/monetization",
  MONETIZATION_ADD: "/monetization/add",
  FEEDBACK: "/feedback",
  SYS_LANGUAGE: "/system/language",
  SYS_LANGUAGE_ADD: "/system/language/add",
  SYS_LANGUAGE_EDIT: (id: string) => `/system/language/${id}/edit`,
  SYS_LOCATION: "/system/location",
  SYS_STATES: "/system/location/states",
  SYS_STATES_ADD: "/system/location/states/add",
  SYS_STATES_EDIT: (id: string) => `/system/location/states/${id}/edit`,
  SYS_DISTRICTS: "/system/location/districts",
  SYS_DISTRICTS_ADD: "/system/location/districts/add",
  SYS_DISTRICTS_EDIT: (id: string) => `/system/location/districts/${id}/edit`,
  SYS_AREAS: "/system/location/areas",
  SYS_AREAS_ADD: "/system/location/areas/add",
  SYS_AREAS_EDIT: (id: string) => `/system/location/areas/${id}/edit`,
  SYS_AUDIT: "/system/audit-logs",
  SYS_BACKUP: "/system/backup",
  SYS_ROLES: "/system/roles",
  SYS_ROLES_ADD: "/system/roles/add",
  SYS_TRANSLATIONS: "/system/translations",
  SETTINGS: "/settings",
  CMS: "/cms",
} as const;

export type AppRoute = Extract<(typeof ROUTES)[keyof typeof ROUTES], string>;
