/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppNewsAllRouteImport } from './routes/_app/news/all'
import { Route as AppNewsAdminRouteImport } from './routes/_app/news/admin'
import { Route as AppNewsAddRouteImport } from './routes/_app/news/add'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsAllRoute = AppNewsAllRouteImport.update({
  id: '/news/all',
  path: '/news/all',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsAdminRoute = AppNewsAdminRouteImport.update({
  id: '/news/admin',
  path: '/news/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsAddRoute = AppNewsAddRouteImport.update({
  id: '/news/add',
  path: '/news/add',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/news/add': typeof AppNewsAddRoute
  '/news/admin': typeof AppNewsAdminRoute
  '/news/all': typeof AppNewsAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/news/add': typeof AppNewsAddRoute
  '/news/admin': typeof AppNewsAdminRoute
  '/news/all': typeof AppNewsAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/news/add': typeof AppNewsAddRoute
  '/_app/news/admin': typeof AppNewsAdminRoute
  '/_app/news/all': typeof AppNewsAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/news/add'
    | '/news/admin'
    | '/news/all'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/news/add' | '/news/admin' | '/news/all'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/news/add'
    | '/_app/news/admin'
    | '/_app/news/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/all': {
      id: '/_app/news/all'
      path: '/news/all'
      fullPath: '/news/all'
      preLoaderRoute: typeof AppNewsAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/admin': {
      id: '/_app/news/admin'
      path: '/news/admin'
      fullPath: '/news/admin'
      preLoaderRoute: typeof AppNewsAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/add': {
      id: '/_app/news/add'
      path: '/news/add'
      fullPath: '/news/add'
      preLoaderRoute: typeof AppNewsAddRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewsAddRoute: typeof AppNewsAddRoute
  AppNewsAdminRoute: typeof AppNewsAdminRoute
  AppNewsAllRoute: typeof AppNewsAllRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNewsAddRoute: AppNewsAddRoute,
  AppNewsAdminRoute: AppNewsAdminRoute,
  AppNewsAllRoute: AppNewsAllRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
