/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppReferralsRouteImport } from './routes/_app/referrals'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppNewsTagsRouteImport } from './routes/_app/news-tags'
import { Route as AppMonetizationRouteImport } from './routes/_app/monetization'
import { Route as AppListingsRouteImport } from './routes/_app/listings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppComplaintsRouteImport } from './routes/_app/complaints'
import { Route as AppCmsRouteImport } from './routes/_app/cms'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppSystemRolesRouteImport } from './routes/_app/system/roles'
import { Route as AppSystemLocationRouteImport } from './routes/_app/system/location'
import { Route as AppSystemLanguageRouteImport } from './routes/_app/system/language'
import { Route as AppSystemBackupRouteImport } from './routes/_app/system/backup'
import { Route as AppSystemAuditLogsRouteImport } from './routes/_app/system/audit-logs'
import { Route as AppOffersAddRouteImport } from './routes/_app/offers/add'
import { Route as AppNotificationsAddRouteImport } from './routes/_app/notifications/add'
import { Route as AppNewsAllRouteImport } from './routes/_app/news/all'
import { Route as AppNewsAdminRouteImport } from './routes/_app/news/admin'
import { Route as AppNewsAddRouteImport } from './routes/_app/news/add'
import { Route as AppMonetizationAddRouteImport } from './routes/_app/monetization/add'
import { Route as AppListingsAddRouteImport } from './routes/_app/listings/add'
import { Route as AppComplaintsComplaintIdRouteImport } from './routes/_app/complaints/$complaintId'
import { Route as AppChannelsAddRouteImport } from './routes/_app/channels/add'
import { Route as AppCategoriesAddRouteImport } from './routes/_app/categories/add'
import { Route as AppNewsNewsIdIndexRouteImport } from './routes/_app/news/$newsId/index'
import { Route as AppChannelsChannelIdIndexRouteImport } from './routes/_app/channels/$channelId/index'
import { Route as AppCategoriesCategoryIdIndexRouteImport } from './routes/_app/categories/$categoryId/index'
import { Route as AppSystemLocationStatesRouteImport } from './routes/_app/system/location/states'
import { Route as AppSystemLocationDistrictsRouteImport } from './routes/_app/system/location/districts'
import { Route as AppSystemLocationAreasRouteImport } from './routes/_app/system/location/areas'
import { Route as AppSystemLanguageAddRouteImport } from './routes/_app/system/language/add'
import { Route as AppNewsNewsIdEditRouteImport } from './routes/_app/news/$newsId/edit'
import { Route as AppChannelsChannelIdEditRouteImport } from './routes/_app/channels/$channelId/edit'
import { Route as AppCategoriesCategoryIdEditRouteImport } from './routes/_app/categories/$categoryId/edit'
import { Route as AppSystemLanguageLanguageIdIndexRouteImport } from './routes/_app/system/language/$languageId/index'
import { Route as AppSystemLocationStatesAddRouteImport } from './routes/_app/system/location/states/add'
import { Route as AppSystemLocationDistrictsAddRouteImport } from './routes/_app/system/location/districts/add'
import { Route as AppSystemLocationAreasAddRouteImport } from './routes/_app/system/location/areas/add'
import { Route as AppSystemLanguageLanguageIdEditRouteImport } from './routes/_app/system/language/$languageId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsTagsRoute = AppNewsTagsRouteImport.update({
  id: '/news-tags',
  path: '/news-tags',
  getParentRoute: () => AppRoute,
} as any)
const AppMonetizationRoute = AppMonetizationRouteImport.update({
  id: '/monetization',
  path: '/monetization',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsRoute = AppListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsRoute = AppCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRolesRoute = AppSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemLocationRoute = AppSystemLocationRouteImport.update({
  id: '/system/location',
  path: '/system/location',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemLanguageRoute = AppSystemLanguageRouteImport.update({
  id: '/system/language',
  path: '/system/language',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemBackupRoute = AppSystemBackupRouteImport.update({
  id: '/system/backup',
  path: '/system/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemAuditLogsRoute = AppSystemAuditLogsRouteImport.update({
  id: '/system/audit-logs',
  path: '/system/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersAddRoute = AppOffersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppOffersRoute,
} as any)
const AppNotificationsAddRoute = AppNotificationsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppNotificationsRoute,
} as any)
const AppNewsAllRoute = AppNewsAllRouteImport.update({
  id: '/news/all',
  path: '/news/all',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsAdminRoute = AppNewsAdminRouteImport.update({
  id: '/news/admin',
  path: '/news/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsAddRoute = AppNewsAddRouteImport.update({
  id: '/news/add',
  path: '/news/add',
  getParentRoute: () => AppRoute,
} as any)
const AppMonetizationAddRoute = AppMonetizationAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppMonetizationRoute,
} as any)
const AppListingsAddRoute = AppListingsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppListingsRoute,
} as any)
const AppComplaintsComplaintIdRoute =
  AppComplaintsComplaintIdRouteImport.update({
    id: '/$complaintId',
    path: '/$complaintId',
    getParentRoute: () => AppComplaintsRoute,
  } as any)
const AppChannelsAddRoute = AppChannelsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppChannelsRoute,
} as any)
const AppCategoriesAddRoute = AppCategoriesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppCategoriesRoute,
} as any)
const AppNewsNewsIdIndexRoute = AppNewsNewsIdIndexRouteImport.update({
  id: '/news/$newsId/',
  path: '/news/$newsId/',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsChannelIdIndexRoute =
  AppChannelsChannelIdIndexRouteImport.update({
    id: '/$channelId/',
    path: '/$channelId/',
    getParentRoute: () => AppChannelsRoute,
  } as any)
const AppCategoriesCategoryIdIndexRoute =
  AppCategoriesCategoryIdIndexRouteImport.update({
    id: '/$categoryId/',
    path: '/$categoryId/',
    getParentRoute: () => AppCategoriesRoute,
  } as any)
const AppSystemLocationStatesRoute = AppSystemLocationStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AppSystemLocationRoute,
} as any)
const AppSystemLocationDistrictsRoute =
  AppSystemLocationDistrictsRouteImport.update({
    id: '/districts',
    path: '/districts',
    getParentRoute: () => AppSystemLocationRoute,
  } as any)
const AppSystemLocationAreasRoute = AppSystemLocationAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AppSystemLocationRoute,
} as any)
const AppSystemLanguageAddRoute = AppSystemLanguageAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppSystemLanguageRoute,
} as any)
const AppNewsNewsIdEditRoute = AppNewsNewsIdEditRouteImport.update({
  id: '/news/$newsId/edit',
  path: '/news/$newsId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsChannelIdEditRoute =
  AppChannelsChannelIdEditRouteImport.update({
    id: '/$channelId/edit',
    path: '/$channelId/edit',
    getParentRoute: () => AppChannelsRoute,
  } as any)
const AppCategoriesCategoryIdEditRoute =
  AppCategoriesCategoryIdEditRouteImport.update({
    id: '/$categoryId/edit',
    path: '/$categoryId/edit',
    getParentRoute: () => AppCategoriesRoute,
  } as any)
const AppSystemLanguageLanguageIdIndexRoute =
  AppSystemLanguageLanguageIdIndexRouteImport.update({
    id: '/$languageId/',
    path: '/$languageId/',
    getParentRoute: () => AppSystemLanguageRoute,
  } as any)
const AppSystemLocationStatesAddRoute =
  AppSystemLocationStatesAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppSystemLocationStatesRoute,
  } as any)
const AppSystemLocationDistrictsAddRoute =
  AppSystemLocationDistrictsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppSystemLocationDistrictsRoute,
  } as any)
const AppSystemLocationAreasAddRoute =
  AppSystemLocationAreasAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppSystemLocationAreasRoute,
  } as any)
const AppSystemLanguageLanguageIdEditRoute =
  AppSystemLanguageLanguageIdEditRouteImport.update({
    id: '/$languageId/edit',
    path: '/$languageId/edit',
    getParentRoute: () => AppSystemLanguageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AppCategoriesRouteWithChildren
  '/channels': typeof AppChannelsRouteWithChildren
  '/cms': typeof AppCmsRoute
  '/complaints': typeof AppComplaintsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/listings': typeof AppListingsRouteWithChildren
  '/monetization': typeof AppMonetizationRouteWithChildren
  '/news-tags': typeof AppNewsTagsRoute
  '/notifications': typeof AppNotificationsRouteWithChildren
  '/offers': typeof AppOffersRouteWithChildren
  '/referrals': typeof AppReferralsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/categories/add': typeof AppCategoriesAddRoute
  '/channels/add': typeof AppChannelsAddRoute
  '/complaints/$complaintId': typeof AppComplaintsComplaintIdRoute
  '/listings/add': typeof AppListingsAddRoute
  '/monetization/add': typeof AppMonetizationAddRoute
  '/news/add': typeof AppNewsAddRoute
  '/news/admin': typeof AppNewsAdminRoute
  '/news/all': typeof AppNewsAllRoute
  '/notifications/add': typeof AppNotificationsAddRoute
  '/offers/add': typeof AppOffersAddRoute
  '/system/audit-logs': typeof AppSystemAuditLogsRoute
  '/system/backup': typeof AppSystemBackupRoute
  '/system/language': typeof AppSystemLanguageRouteWithChildren
  '/system/location': typeof AppSystemLocationRouteWithChildren
  '/system/roles': typeof AppSystemRolesRoute
  '/categories/$categoryId/edit': typeof AppCategoriesCategoryIdEditRoute
  '/channels/$channelId/edit': typeof AppChannelsChannelIdEditRoute
  '/news/$newsId/edit': typeof AppNewsNewsIdEditRoute
  '/system/language/add': typeof AppSystemLanguageAddRoute
  '/system/location/areas': typeof AppSystemLocationAreasRouteWithChildren
  '/system/location/districts': typeof AppSystemLocationDistrictsRouteWithChildren
  '/system/location/states': typeof AppSystemLocationStatesRouteWithChildren
  '/categories/$categoryId/': typeof AppCategoriesCategoryIdIndexRoute
  '/channels/$channelId/': typeof AppChannelsChannelIdIndexRoute
  '/news/$newsId/': typeof AppNewsNewsIdIndexRoute
  '/system/language/$languageId/edit': typeof AppSystemLanguageLanguageIdEditRoute
  '/system/location/areas/add': typeof AppSystemLocationAreasAddRoute
  '/system/location/districts/add': typeof AppSystemLocationDistrictsAddRoute
  '/system/location/states/add': typeof AppSystemLocationStatesAddRoute
  '/system/language/$languageId/': typeof AppSystemLanguageLanguageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AppCategoriesRouteWithChildren
  '/channels': typeof AppChannelsRouteWithChildren
  '/cms': typeof AppCmsRoute
  '/complaints': typeof AppComplaintsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/listings': typeof AppListingsRouteWithChildren
  '/monetization': typeof AppMonetizationRouteWithChildren
  '/news-tags': typeof AppNewsTagsRoute
  '/notifications': typeof AppNotificationsRouteWithChildren
  '/offers': typeof AppOffersRouteWithChildren
  '/referrals': typeof AppReferralsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/categories/add': typeof AppCategoriesAddRoute
  '/channels/add': typeof AppChannelsAddRoute
  '/complaints/$complaintId': typeof AppComplaintsComplaintIdRoute
  '/listings/add': typeof AppListingsAddRoute
  '/monetization/add': typeof AppMonetizationAddRoute
  '/news/add': typeof AppNewsAddRoute
  '/news/admin': typeof AppNewsAdminRoute
  '/news/all': typeof AppNewsAllRoute
  '/notifications/add': typeof AppNotificationsAddRoute
  '/offers/add': typeof AppOffersAddRoute
  '/system/audit-logs': typeof AppSystemAuditLogsRoute
  '/system/backup': typeof AppSystemBackupRoute
  '/system/language': typeof AppSystemLanguageRouteWithChildren
  '/system/location': typeof AppSystemLocationRouteWithChildren
  '/system/roles': typeof AppSystemRolesRoute
  '/categories/$categoryId/edit': typeof AppCategoriesCategoryIdEditRoute
  '/channels/$channelId/edit': typeof AppChannelsChannelIdEditRoute
  '/news/$newsId/edit': typeof AppNewsNewsIdEditRoute
  '/system/language/add': typeof AppSystemLanguageAddRoute
  '/system/location/areas': typeof AppSystemLocationAreasRouteWithChildren
  '/system/location/districts': typeof AppSystemLocationDistrictsRouteWithChildren
  '/system/location/states': typeof AppSystemLocationStatesRouteWithChildren
  '/categories/$categoryId': typeof AppCategoriesCategoryIdIndexRoute
  '/channels/$channelId': typeof AppChannelsChannelIdIndexRoute
  '/news/$newsId': typeof AppNewsNewsIdIndexRoute
  '/system/language/$languageId/edit': typeof AppSystemLanguageLanguageIdEditRoute
  '/system/location/areas/add': typeof AppSystemLocationAreasAddRoute
  '/system/location/districts/add': typeof AppSystemLocationDistrictsAddRoute
  '/system/location/states/add': typeof AppSystemLocationStatesAddRoute
  '/system/language/$languageId': typeof AppSystemLanguageLanguageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/categories': typeof AppCategoriesRouteWithChildren
  '/_app/channels': typeof AppChannelsRouteWithChildren
  '/_app/cms': typeof AppCmsRoute
  '/_app/complaints': typeof AppComplaintsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/listings': typeof AppListingsRouteWithChildren
  '/_app/monetization': typeof AppMonetizationRouteWithChildren
  '/_app/news-tags': typeof AppNewsTagsRoute
  '/_app/notifications': typeof AppNotificationsRouteWithChildren
  '/_app/offers': typeof AppOffersRouteWithChildren
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/categories/add': typeof AppCategoriesAddRoute
  '/_app/channels/add': typeof AppChannelsAddRoute
  '/_app/complaints/$complaintId': typeof AppComplaintsComplaintIdRoute
  '/_app/listings/add': typeof AppListingsAddRoute
  '/_app/monetization/add': typeof AppMonetizationAddRoute
  '/_app/news/add': typeof AppNewsAddRoute
  '/_app/news/admin': typeof AppNewsAdminRoute
  '/_app/news/all': typeof AppNewsAllRoute
  '/_app/notifications/add': typeof AppNotificationsAddRoute
  '/_app/offers/add': typeof AppOffersAddRoute
  '/_app/system/audit-logs': typeof AppSystemAuditLogsRoute
  '/_app/system/backup': typeof AppSystemBackupRoute
  '/_app/system/language': typeof AppSystemLanguageRouteWithChildren
  '/_app/system/location': typeof AppSystemLocationRouteWithChildren
  '/_app/system/roles': typeof AppSystemRolesRoute
  '/_app/categories/$categoryId/edit': typeof AppCategoriesCategoryIdEditRoute
  '/_app/channels/$channelId/edit': typeof AppChannelsChannelIdEditRoute
  '/_app/news/$newsId/edit': typeof AppNewsNewsIdEditRoute
  '/_app/system/language/add': typeof AppSystemLanguageAddRoute
  '/_app/system/location/areas': typeof AppSystemLocationAreasRouteWithChildren
  '/_app/system/location/districts': typeof AppSystemLocationDistrictsRouteWithChildren
  '/_app/system/location/states': typeof AppSystemLocationStatesRouteWithChildren
  '/_app/categories/$categoryId/': typeof AppCategoriesCategoryIdIndexRoute
  '/_app/channels/$channelId/': typeof AppChannelsChannelIdIndexRoute
  '/_app/news/$newsId/': typeof AppNewsNewsIdIndexRoute
  '/_app/system/language/$languageId/edit': typeof AppSystemLanguageLanguageIdEditRoute
  '/_app/system/location/areas/add': typeof AppSystemLocationAreasAddRoute
  '/_app/system/location/districts/add': typeof AppSystemLocationDistrictsAddRoute
  '/_app/system/location/states/add': typeof AppSystemLocationStatesAddRoute
  '/_app/system/language/$languageId/': typeof AppSystemLanguageLanguageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/channels'
    | '/cms'
    | '/complaints'
    | '/dashboard'
    | '/listings'
    | '/monetization'
    | '/news-tags'
    | '/notifications'
    | '/offers'
    | '/referrals'
    | '/reports'
    | '/settings'
    | '/users'
    | '/categories/add'
    | '/channels/add'
    | '/complaints/$complaintId'
    | '/listings/add'
    | '/monetization/add'
    | '/news/add'
    | '/news/admin'
    | '/news/all'
    | '/notifications/add'
    | '/offers/add'
    | '/system/audit-logs'
    | '/system/backup'
    | '/system/language'
    | '/system/location'
    | '/system/roles'
    | '/categories/$categoryId/edit'
    | '/channels/$channelId/edit'
    | '/news/$newsId/edit'
    | '/system/language/add'
    | '/system/location/areas'
    | '/system/location/districts'
    | '/system/location/states'
    | '/categories/$categoryId/'
    | '/channels/$channelId/'
    | '/news/$newsId/'
    | '/system/language/$languageId/edit'
    | '/system/location/areas/add'
    | '/system/location/districts/add'
    | '/system/location/states/add'
    | '/system/language/$languageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/channels'
    | '/cms'
    | '/complaints'
    | '/dashboard'
    | '/listings'
    | '/monetization'
    | '/news-tags'
    | '/notifications'
    | '/offers'
    | '/referrals'
    | '/reports'
    | '/settings'
    | '/users'
    | '/categories/add'
    | '/channels/add'
    | '/complaints/$complaintId'
    | '/listings/add'
    | '/monetization/add'
    | '/news/add'
    | '/news/admin'
    | '/news/all'
    | '/notifications/add'
    | '/offers/add'
    | '/system/audit-logs'
    | '/system/backup'
    | '/system/language'
    | '/system/location'
    | '/system/roles'
    | '/categories/$categoryId/edit'
    | '/channels/$channelId/edit'
    | '/news/$newsId/edit'
    | '/system/language/add'
    | '/system/location/areas'
    | '/system/location/districts'
    | '/system/location/states'
    | '/categories/$categoryId'
    | '/channels/$channelId'
    | '/news/$newsId'
    | '/system/language/$languageId/edit'
    | '/system/location/areas/add'
    | '/system/location/districts/add'
    | '/system/location/states/add'
    | '/system/language/$languageId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/categories'
    | '/_app/channels'
    | '/_app/cms'
    | '/_app/complaints'
    | '/_app/dashboard'
    | '/_app/listings'
    | '/_app/monetization'
    | '/_app/news-tags'
    | '/_app/notifications'
    | '/_app/offers'
    | '/_app/referrals'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/categories/add'
    | '/_app/channels/add'
    | '/_app/complaints/$complaintId'
    | '/_app/listings/add'
    | '/_app/monetization/add'
    | '/_app/news/add'
    | '/_app/news/admin'
    | '/_app/news/all'
    | '/_app/notifications/add'
    | '/_app/offers/add'
    | '/_app/system/audit-logs'
    | '/_app/system/backup'
    | '/_app/system/language'
    | '/_app/system/location'
    | '/_app/system/roles'
    | '/_app/categories/$categoryId/edit'
    | '/_app/channels/$channelId/edit'
    | '/_app/news/$newsId/edit'
    | '/_app/system/language/add'
    | '/_app/system/location/areas'
    | '/_app/system/location/districts'
    | '/_app/system/location/states'
    | '/_app/categories/$categoryId/'
    | '/_app/channels/$channelId/'
    | '/_app/news/$newsId/'
    | '/_app/system/language/$languageId/edit'
    | '/_app/system/location/areas/add'
    | '/_app/system/location/districts/add'
    | '/_app/system/location/states/add'
    | '/_app/system/language/$languageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news-tags': {
      id: '/_app/news-tags'
      path: '/news-tags'
      fullPath: '/news-tags'
      preLoaderRoute: typeof AppNewsTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monetization': {
      id: '/_app/monetization'
      path: '/monetization'
      fullPath: '/monetization'
      preLoaderRoute: typeof AppMonetizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings': {
      id: '/_app/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AppListingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cms': {
      id: '/_app/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AppCmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/roles': {
      id: '/_app/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof AppSystemRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/location': {
      id: '/_app/system/location'
      path: '/system/location'
      fullPath: '/system/location'
      preLoaderRoute: typeof AppSystemLocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/language': {
      id: '/_app/system/language'
      path: '/system/language'
      fullPath: '/system/language'
      preLoaderRoute: typeof AppSystemLanguageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/backup': {
      id: '/_app/system/backup'
      path: '/system/backup'
      fullPath: '/system/backup'
      preLoaderRoute: typeof AppSystemBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/audit-logs': {
      id: '/_app/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/system/audit-logs'
      preLoaderRoute: typeof AppSystemAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers/add': {
      id: '/_app/offers/add'
      path: '/add'
      fullPath: '/offers/add'
      preLoaderRoute: typeof AppOffersAddRouteImport
      parentRoute: typeof AppOffersRoute
    }
    '/_app/notifications/add': {
      id: '/_app/notifications/add'
      path: '/add'
      fullPath: '/notifications/add'
      preLoaderRoute: typeof AppNotificationsAddRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/news/all': {
      id: '/_app/news/all'
      path: '/news/all'
      fullPath: '/news/all'
      preLoaderRoute: typeof AppNewsAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/admin': {
      id: '/_app/news/admin'
      path: '/news/admin'
      fullPath: '/news/admin'
      preLoaderRoute: typeof AppNewsAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/add': {
      id: '/_app/news/add'
      path: '/news/add'
      fullPath: '/news/add'
      preLoaderRoute: typeof AppNewsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monetization/add': {
      id: '/_app/monetization/add'
      path: '/add'
      fullPath: '/monetization/add'
      preLoaderRoute: typeof AppMonetizationAddRouteImport
      parentRoute: typeof AppMonetizationRoute
    }
    '/_app/listings/add': {
      id: '/_app/listings/add'
      path: '/add'
      fullPath: '/listings/add'
      preLoaderRoute: typeof AppListingsAddRouteImport
      parentRoute: typeof AppListingsRoute
    }
    '/_app/complaints/$complaintId': {
      id: '/_app/complaints/$complaintId'
      path: '/$complaintId'
      fullPath: '/complaints/$complaintId'
      preLoaderRoute: typeof AppComplaintsComplaintIdRouteImport
      parentRoute: typeof AppComplaintsRoute
    }
    '/_app/channels/add': {
      id: '/_app/channels/add'
      path: '/add'
      fullPath: '/channels/add'
      preLoaderRoute: typeof AppChannelsAddRouteImport
      parentRoute: typeof AppChannelsRoute
    }
    '/_app/categories/add': {
      id: '/_app/categories/add'
      path: '/add'
      fullPath: '/categories/add'
      preLoaderRoute: typeof AppCategoriesAddRouteImport
      parentRoute: typeof AppCategoriesRoute
    }
    '/_app/news/$newsId/': {
      id: '/_app/news/$newsId/'
      path: '/news/$newsId'
      fullPath: '/news/$newsId/'
      preLoaderRoute: typeof AppNewsNewsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/$channelId/': {
      id: '/_app/channels/$channelId/'
      path: '/$channelId'
      fullPath: '/channels/$channelId/'
      preLoaderRoute: typeof AppChannelsChannelIdIndexRouteImport
      parentRoute: typeof AppChannelsRoute
    }
    '/_app/categories/$categoryId/': {
      id: '/_app/categories/$categoryId/'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId/'
      preLoaderRoute: typeof AppCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AppCategoriesRoute
    }
    '/_app/system/location/states': {
      id: '/_app/system/location/states'
      path: '/states'
      fullPath: '/system/location/states'
      preLoaderRoute: typeof AppSystemLocationStatesRouteImport
      parentRoute: typeof AppSystemLocationRoute
    }
    '/_app/system/location/districts': {
      id: '/_app/system/location/districts'
      path: '/districts'
      fullPath: '/system/location/districts'
      preLoaderRoute: typeof AppSystemLocationDistrictsRouteImport
      parentRoute: typeof AppSystemLocationRoute
    }
    '/_app/system/location/areas': {
      id: '/_app/system/location/areas'
      path: '/areas'
      fullPath: '/system/location/areas'
      preLoaderRoute: typeof AppSystemLocationAreasRouteImport
      parentRoute: typeof AppSystemLocationRoute
    }
    '/_app/system/language/add': {
      id: '/_app/system/language/add'
      path: '/add'
      fullPath: '/system/language/add'
      preLoaderRoute: typeof AppSystemLanguageAddRouteImport
      parentRoute: typeof AppSystemLanguageRoute
    }
    '/_app/news/$newsId/edit': {
      id: '/_app/news/$newsId/edit'
      path: '/news/$newsId/edit'
      fullPath: '/news/$newsId/edit'
      preLoaderRoute: typeof AppNewsNewsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/$channelId/edit': {
      id: '/_app/channels/$channelId/edit'
      path: '/$channelId/edit'
      fullPath: '/channels/$channelId/edit'
      preLoaderRoute: typeof AppChannelsChannelIdEditRouteImport
      parentRoute: typeof AppChannelsRoute
    }
    '/_app/categories/$categoryId/edit': {
      id: '/_app/categories/$categoryId/edit'
      path: '/$categoryId/edit'
      fullPath: '/categories/$categoryId/edit'
      preLoaderRoute: typeof AppCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AppCategoriesRoute
    }
    '/_app/system/language/$languageId/': {
      id: '/_app/system/language/$languageId/'
      path: '/$languageId'
      fullPath: '/system/language/$languageId/'
      preLoaderRoute: typeof AppSystemLanguageLanguageIdIndexRouteImport
      parentRoute: typeof AppSystemLanguageRoute
    }
    '/_app/system/location/states/add': {
      id: '/_app/system/location/states/add'
      path: '/add'
      fullPath: '/system/location/states/add'
      preLoaderRoute: typeof AppSystemLocationStatesAddRouteImport
      parentRoute: typeof AppSystemLocationStatesRoute
    }
    '/_app/system/location/districts/add': {
      id: '/_app/system/location/districts/add'
      path: '/add'
      fullPath: '/system/location/districts/add'
      preLoaderRoute: typeof AppSystemLocationDistrictsAddRouteImport
      parentRoute: typeof AppSystemLocationDistrictsRoute
    }
    '/_app/system/location/areas/add': {
      id: '/_app/system/location/areas/add'
      path: '/add'
      fullPath: '/system/location/areas/add'
      preLoaderRoute: typeof AppSystemLocationAreasAddRouteImport
      parentRoute: typeof AppSystemLocationAreasRoute
    }
    '/_app/system/language/$languageId/edit': {
      id: '/_app/system/language/$languageId/edit'
      path: '/$languageId/edit'
      fullPath: '/system/language/$languageId/edit'
      preLoaderRoute: typeof AppSystemLanguageLanguageIdEditRouteImport
      parentRoute: typeof AppSystemLanguageRoute
    }
  }
}

interface AppCategoriesRouteChildren {
  AppCategoriesAddRoute: typeof AppCategoriesAddRoute
  AppCategoriesCategoryIdEditRoute: typeof AppCategoriesCategoryIdEditRoute
  AppCategoriesCategoryIdIndexRoute: typeof AppCategoriesCategoryIdIndexRoute
}

const AppCategoriesRouteChildren: AppCategoriesRouteChildren = {
  AppCategoriesAddRoute: AppCategoriesAddRoute,
  AppCategoriesCategoryIdEditRoute: AppCategoriesCategoryIdEditRoute,
  AppCategoriesCategoryIdIndexRoute: AppCategoriesCategoryIdIndexRoute,
}

const AppCategoriesRouteWithChildren = AppCategoriesRoute._addFileChildren(
  AppCategoriesRouteChildren,
)

interface AppChannelsRouteChildren {
  AppChannelsAddRoute: typeof AppChannelsAddRoute
  AppChannelsChannelIdEditRoute: typeof AppChannelsChannelIdEditRoute
  AppChannelsChannelIdIndexRoute: typeof AppChannelsChannelIdIndexRoute
}

const AppChannelsRouteChildren: AppChannelsRouteChildren = {
  AppChannelsAddRoute: AppChannelsAddRoute,
  AppChannelsChannelIdEditRoute: AppChannelsChannelIdEditRoute,
  AppChannelsChannelIdIndexRoute: AppChannelsChannelIdIndexRoute,
}

const AppChannelsRouteWithChildren = AppChannelsRoute._addFileChildren(
  AppChannelsRouteChildren,
)

interface AppComplaintsRouteChildren {
  AppComplaintsComplaintIdRoute: typeof AppComplaintsComplaintIdRoute
}

const AppComplaintsRouteChildren: AppComplaintsRouteChildren = {
  AppComplaintsComplaintIdRoute: AppComplaintsComplaintIdRoute,
}

const AppComplaintsRouteWithChildren = AppComplaintsRoute._addFileChildren(
  AppComplaintsRouteChildren,
)

interface AppListingsRouteChildren {
  AppListingsAddRoute: typeof AppListingsAddRoute
}

const AppListingsRouteChildren: AppListingsRouteChildren = {
  AppListingsAddRoute: AppListingsAddRoute,
}

const AppListingsRouteWithChildren = AppListingsRoute._addFileChildren(
  AppListingsRouteChildren,
)

interface AppMonetizationRouteChildren {
  AppMonetizationAddRoute: typeof AppMonetizationAddRoute
}

const AppMonetizationRouteChildren: AppMonetizationRouteChildren = {
  AppMonetizationAddRoute: AppMonetizationAddRoute,
}

const AppMonetizationRouteWithChildren = AppMonetizationRoute._addFileChildren(
  AppMonetizationRouteChildren,
)

interface AppNotificationsRouteChildren {
  AppNotificationsAddRoute: typeof AppNotificationsAddRoute
}

const AppNotificationsRouteChildren: AppNotificationsRouteChildren = {
  AppNotificationsAddRoute: AppNotificationsAddRoute,
}

const AppNotificationsRouteWithChildren =
  AppNotificationsRoute._addFileChildren(AppNotificationsRouteChildren)

interface AppOffersRouteChildren {
  AppOffersAddRoute: typeof AppOffersAddRoute
}

const AppOffersRouteChildren: AppOffersRouteChildren = {
  AppOffersAddRoute: AppOffersAddRoute,
}

const AppOffersRouteWithChildren = AppOffersRoute._addFileChildren(
  AppOffersRouteChildren,
)

interface AppSystemLanguageRouteChildren {
  AppSystemLanguageAddRoute: typeof AppSystemLanguageAddRoute
  AppSystemLanguageLanguageIdEditRoute: typeof AppSystemLanguageLanguageIdEditRoute
  AppSystemLanguageLanguageIdIndexRoute: typeof AppSystemLanguageLanguageIdIndexRoute
}

const AppSystemLanguageRouteChildren: AppSystemLanguageRouteChildren = {
  AppSystemLanguageAddRoute: AppSystemLanguageAddRoute,
  AppSystemLanguageLanguageIdEditRoute: AppSystemLanguageLanguageIdEditRoute,
  AppSystemLanguageLanguageIdIndexRoute: AppSystemLanguageLanguageIdIndexRoute,
}

const AppSystemLanguageRouteWithChildren =
  AppSystemLanguageRoute._addFileChildren(AppSystemLanguageRouteChildren)

interface AppSystemLocationAreasRouteChildren {
  AppSystemLocationAreasAddRoute: typeof AppSystemLocationAreasAddRoute
}

const AppSystemLocationAreasRouteChildren: AppSystemLocationAreasRouteChildren =
  {
    AppSystemLocationAreasAddRoute: AppSystemLocationAreasAddRoute,
  }

const AppSystemLocationAreasRouteWithChildren =
  AppSystemLocationAreasRoute._addFileChildren(
    AppSystemLocationAreasRouteChildren,
  )

interface AppSystemLocationDistrictsRouteChildren {
  AppSystemLocationDistrictsAddRoute: typeof AppSystemLocationDistrictsAddRoute
}

const AppSystemLocationDistrictsRouteChildren: AppSystemLocationDistrictsRouteChildren =
  {
    AppSystemLocationDistrictsAddRoute: AppSystemLocationDistrictsAddRoute,
  }

const AppSystemLocationDistrictsRouteWithChildren =
  AppSystemLocationDistrictsRoute._addFileChildren(
    AppSystemLocationDistrictsRouteChildren,
  )

interface AppSystemLocationStatesRouteChildren {
  AppSystemLocationStatesAddRoute: typeof AppSystemLocationStatesAddRoute
}

const AppSystemLocationStatesRouteChildren: AppSystemLocationStatesRouteChildren =
  {
    AppSystemLocationStatesAddRoute: AppSystemLocationStatesAddRoute,
  }

const AppSystemLocationStatesRouteWithChildren =
  AppSystemLocationStatesRoute._addFileChildren(
    AppSystemLocationStatesRouteChildren,
  )

interface AppSystemLocationRouteChildren {
  AppSystemLocationAreasRoute: typeof AppSystemLocationAreasRouteWithChildren
  AppSystemLocationDistrictsRoute: typeof AppSystemLocationDistrictsRouteWithChildren
  AppSystemLocationStatesRoute: typeof AppSystemLocationStatesRouteWithChildren
}

const AppSystemLocationRouteChildren: AppSystemLocationRouteChildren = {
  AppSystemLocationAreasRoute: AppSystemLocationAreasRouteWithChildren,
  AppSystemLocationDistrictsRoute: AppSystemLocationDistrictsRouteWithChildren,
  AppSystemLocationStatesRoute: AppSystemLocationStatesRouteWithChildren,
}

const AppSystemLocationRouteWithChildren =
  AppSystemLocationRoute._addFileChildren(AppSystemLocationRouteChildren)

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRouteWithChildren
  AppChannelsRoute: typeof AppChannelsRouteWithChildren
  AppCmsRoute: typeof AppCmsRoute
  AppComplaintsRoute: typeof AppComplaintsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppListingsRoute: typeof AppListingsRouteWithChildren
  AppMonetizationRoute: typeof AppMonetizationRouteWithChildren
  AppNewsTagsRoute: typeof AppNewsTagsRoute
  AppNotificationsRoute: typeof AppNotificationsRouteWithChildren
  AppOffersRoute: typeof AppOffersRouteWithChildren
  AppReferralsRoute: typeof AppReferralsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppNewsAddRoute: typeof AppNewsAddRoute
  AppNewsAdminRoute: typeof AppNewsAdminRoute
  AppNewsAllRoute: typeof AppNewsAllRoute
  AppSystemAuditLogsRoute: typeof AppSystemAuditLogsRoute
  AppSystemBackupRoute: typeof AppSystemBackupRoute
  AppSystemLanguageRoute: typeof AppSystemLanguageRouteWithChildren
  AppSystemLocationRoute: typeof AppSystemLocationRouteWithChildren
  AppSystemRolesRoute: typeof AppSystemRolesRoute
  AppNewsNewsIdEditRoute: typeof AppNewsNewsIdEditRoute
  AppNewsNewsIdIndexRoute: typeof AppNewsNewsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRouteWithChildren,
  AppChannelsRoute: AppChannelsRouteWithChildren,
  AppCmsRoute: AppCmsRoute,
  AppComplaintsRoute: AppComplaintsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppListingsRoute: AppListingsRouteWithChildren,
  AppMonetizationRoute: AppMonetizationRouteWithChildren,
  AppNewsTagsRoute: AppNewsTagsRoute,
  AppNotificationsRoute: AppNotificationsRouteWithChildren,
  AppOffersRoute: AppOffersRouteWithChildren,
  AppReferralsRoute: AppReferralsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppNewsAddRoute: AppNewsAddRoute,
  AppNewsAdminRoute: AppNewsAdminRoute,
  AppNewsAllRoute: AppNewsAllRoute,
  AppSystemAuditLogsRoute: AppSystemAuditLogsRoute,
  AppSystemBackupRoute: AppSystemBackupRoute,
  AppSystemLanguageRoute: AppSystemLanguageRouteWithChildren,
  AppSystemLocationRoute: AppSystemLocationRouteWithChildren,
  AppSystemRolesRoute: AppSystemRolesRoute,
  AppNewsNewsIdEditRoute: AppNewsNewsIdEditRoute,
  AppNewsNewsIdIndexRoute: AppNewsNewsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
